#!/usr/bin/env fish
# Configure a per-user macOS Emacs daemon and Fish client commands.

set -l generated_marker 'Managed by setup-macos-emacs-daemon.fish'
set -l service_label 'user.emacs.daemon'
set -l daemon_name 'main'
set -l emacs_bin '/opt/homebrew/bin/emacs'
set -l emacsclient_bin '/opt/homebrew/bin/emacsclient'

function fail --argument-names message
    echo "Error: $message" >&2
    exit 1
end

function replace_generated_file --argument-names target content marker
    if test -e "$target"; and not grep -Fq -- "$marker" "$target"
        fail "Refusing to overwrite $target because it was not generated by this script."
    end

    set -l temporary_file (mktemp "$target.XXXXXX")
    or fail "Could not create a temporary file next to $target."

    printf '%s\n' "$content" >"$temporary_file"
    or begin
        rm -f "$temporary_file"
        fail "Could not write $target."
    end

    mv "$temporary_file" "$target"
    or fail "Could not replace $target."
end

if not test (uname) = Darwin
    fail 'This installer only supports macOS.'
end

for required_command in launchctl plutil grep mktemp
    command -sq "$required_command"
    or fail "Required command not found: $required_command"
end

test -x "$emacs_bin"
or fail "Expected Homebrew Emacs at $emacs_bin. Install it first, then rerun this script."
test -x "$emacsclient_bin"
or fail "Expected Homebrew emacsclient at $emacsclient_bin. Install it first, then rerun this script."

set -l launch_agents_dir "$HOME/Library/LaunchAgents"
set -l log_dir "$HOME/Library/Logs"
set -l fish_functions_dir "$HOME/.config/fish/functions"
set -l plist_path "$launch_agents_dir/$service_label.plist"
set -l e_function_path "$fish_functions_dir/e.fish"
set -l eg_function_path "$fish_functions_dir/eg.fish"
set -l user_id (id -u)

mkdir -p "$launch_agents_dir" "$log_dir" "$fish_functions_dir"
or fail 'Could not create the required user configuration directories.'

set -l service_was_loaded false
if launchctl print "gui/$user_id/$service_label" >/dev/null 2>&1
    set service_was_loaded true
else if "$emacsclient_bin" -s "$daemon_name" --eval t >/dev/null 2>&1
    fail "An Emacs server named '$daemon_name' is already running. Stop that server, then rerun this script."
end

set -l plist_content "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<!-- $generated_marker -->
<plist version=\"1.0\">
<dict>
  <key>Label</key>
  <string>$service_label</string>
  <key>ProgramArguments</key>
  <array>
    <string>$emacs_bin</string>
    <string>--fg-daemon=$daemon_name</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>ProcessType</key>
  <string>Background</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$log_dir/emacs-daemon.log</string>
  <key>StandardErrorPath</key>
  <string>$log_dir/emacs-daemon-error.log</string>
</dict>
</plist>"

set -l e_function_content "# $generated_marker
function e --description 'Edit files in a terminal Emacs client'
    $emacsclient_bin -s $daemon_name -t \$argv
end"

set -l eg_function_content "# $generated_marker
function eg --description 'Edit files in a graphical Emacs client frame'
    $emacsclient_bin -s $daemon_name -c \$argv
end"

replace_generated_file "$plist_path" "$plist_content" "$generated_marker"
plutil -lint "$plist_path" >/dev/null
or fail "Generated LaunchAgent plist is invalid: $plist_path"

replace_generated_file "$e_function_path" "$e_function_content" "$generated_marker"
replace_generated_file "$eg_function_path" "$eg_function_content" "$generated_marker"

if $service_was_loaded
    launchctl bootout "gui/$user_id/$service_label"
    or fail "Could not unload the existing $service_label service."
end

for attempt in (seq 1 20)
    if not "$emacsclient_bin" -s "$daemon_name" --eval t >/dev/null 2>&1
        break
    end

    if $service_was_loaded
        # A prior version used --daemon, which detaches from launchd.  Stop a
        # lingering server from that managed service before replacing it.
        "$emacsclient_bin" -s "$daemon_name" --eval '(kill-emacs)' >/dev/null 2>&1
    end
    sleep 0.25
end

if "$emacsclient_bin" -s "$daemon_name" --eval t >/dev/null 2>&1
    fail "An Emacs server named '$daemon_name' is still running. Stop that server, then rerun this script."
end

launchctl bootstrap "gui/$user_id" "$plist_path"
or fail "Could not load $plist_path."
launchctl kickstart -k "gui/$user_id/$service_label"
or fail "Could not start $service_label."

set -l daemon_pid ''
for attempt in (seq 1 20)
    set daemon_pid ("$emacsclient_bin" -s "$daemon_name" --eval '(emacs-pid)' 2>/dev/null)
    if test $status -eq 0
        break
    end
    sleep 0.25
end

if test -z "$daemon_pid"
    echo "The LaunchAgent was installed, but the daemon did not become reachable." >&2
    echo "Inspect $log_dir/emacs-daemon-error.log for details." >&2
    exit 1
end

echo "Emacs daemon '$daemon_name' is running (PID $daemon_pid)."
echo "Fish commands installed: e <file> (terminal), eg <file> (graphical frame)."
echo "Open a new Fish shell, or run: source $e_function_path; source $eg_function_path"
